name: mlm-course
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - jupyter>=1.0.0
  - jupyterlab>=3.0.0
  - ipywidgets>=7.6.0
  - scikit-learn>=1.0.0
  - pandas>=1.3.0
  - sympy>=1.8.0
  - plotly>=5.0.0
  - bokeh>=2.3.0
  - numba>=0.54.0
  - pytest>=6.0.0
  - black>=21.0.0
  - flake8>=3.9.0
  - pip
  - pip:
    - manim>=0.15.0
